#!/bin/bash

bupdir="/volumeSATA1/satashare1-1"

if [[ ! -d "$bupdir/@$1@" ]] ; then
	echo "$0: $bupdir/@$1@: directory not found" >&2
	echo "usage:   $0 olddisksetname_disknum newdisksetname_disknum" >&2
	echo "example: $0 20181007_005 20190312_005" >&2
	exit 1
fi

if [[ -d "$bupdir/$1" ]] ; then
	# cleanup old mount directory
	rmdir "$bupdir/$1"
fi

if [[ -d "$bupdir/$2" ]] ; then
	# target dir may already be mounted - unmount and cleanup
	umount "$bupdir/$2"
	rmdir "$bupdir/$2"
fi

if [[ -d "$bupdir/@$1@" && ! -d "$bupdir/@$2@" ]] ; then
	mv -v "$bupdir/@$1@" "$bupdir/@$2@"
fi

backup_diskset_copy "$2" mountonly

#EOF
