#!/bin/bash

bupdir="/volumeSATA1/satashare1-1"
if [[ ! -d "$bupdir/@$1@" ]] ; then
	echo "usage:   $0 olddisksetname_disknum newdisksetname_disknum"
	echo "example: $0 20181007_005 20190312_005"
	exit 1
fi

if [[ -d "$bupdir/$1" ]] ; then
	rmdir "$bupdir/$1"
fi
mv -v "$bupdir/@$1@" "$bupdir/@$2@"
backup_diskset_copy $2 mountonly

#EOF
