#!/bin/bash

for i in "$@" ; do

if [ -e "$i" ] ; then
	if true ; then
		# use GNU find -printf format
		find "$i" -type f \( ! -path "*/#recycle/*" ! -path "*/@eaDir/*" ! -path "*-/*" \) -printf "%TY%Tm%Td_%TH%TM%TS\t%s\t\t%p\n" | sed -e 's/\(^........_......\)\.[0-9]*/\1/'
	else
		# use date and ls to get the moddate and size. stat could also be used, but stat tends to have different format specifiers on different systems
		find "$i" -type f \( ! -path "*/#recycle/*" ! -path "*/@eaDir/*" ! -path "*-/*" \) -print | while read f ; do
			a=$(date -r "$f" +%Y%m%d_%H%M%S)
			b=$(ls -l "$f" | sed -e 's/ /\t/g' | cut -f 5)
			echo -e "$a\t$b\t\t$f"
		done
	fi
else
	echo "usage: mkfilelist_fast file|directory [file|directory ...]"
	echo "print on stdout a list with"
	echo "modification date<tab>file length<tab><tab>file path"
fi

done

#EOF
