#!/bin/bash
# count the #entries inside $1 and filter out the @eaDir directory. an empty dir gives (count=0)
if (( $(find "$1" -mindepth 1 -maxdepth 1 ! -path '*/@eaDir' -print | wc -l) == 0 )) ; then
	exit 0
fi
exit 1
#EOF
