#!/bin/bash
# a special version of rmdir that also removes the @SynoEAStream and @SynoResource in the ../@eaDir directory
# $1 must be a directory
if [[ -d "$1" ]] ; then
	# if there are no files or directories in $1 (empty dir), first delete the stray @eaDir subdirectory, if any (or else the directory is not truly empty)
	if isemptydir_with_ea "$1" && rm -rf "$1/@eaDir" && rmdir "$1" ; then
		rm -f "$(dirname "$1")/@eaDir/$(basename "$1")@SynoEAStream"
		rm -f "$(dirname "$1")/@eaDir/$(basename "$1")@SynoResource"
		exit 0
	else
		echo "$0: $1: directory not empty" >&2
		exit 1
	fi
else
	echo "$0: $1: not a directory" >&2
	exit 1
fi
#EOF
