#!/bin/bash
# cleanup directories with linked files: check for files.ext or symlinks~ in dir_with_links, not found in the file
# file_with_linked_filepaths_list (originals have probably been renamed or deleted)
# the script matches the full path of the files found in dir_with_links with the file paths found in file_with_linked_file_list
# -n performs a dryrun (prints what the script will do, use before screwing up your file system unintentionally)
# -d also cleans up any empty directories (i.e. all linked files in that directory have been deleted), but preserves tagged directories
# -t moves files and directories to the indicated trash_dir
# note: cleans up files and symlinks (to a file or a directory) but skips files with a link count of 1
# note: does not assume that file_with_linked_filepaths_list is sorted - this script will sort this list because we use diff to match with the files found in dir
#
# check parameters
if [[ $# == 0 ]] ; then echo "usage: cleanup_links [-n] [-d] [-t trash_dir] dir_with_links [dir ...] file_with_linked_filepaths_list" >&2 ; exit 1 ; fi
if [[ $1 == -n ]] ; then dryrun=y ; echo "cleanup_links >>> DRYRUN/DEBUG mode <<<" ; shift ; fi
if [[ $1 == -d ]] ; then cleanupdirs=y ; shift ; fi
if [[ $1 == -t ]] ; then if [[ -d "$2" ]] ; then trash=$2 ; shift 2 ; else echo "illegal option: $1 $2" >&2 ; exit 1 ; fi ; fi
dir=("${@:1:$#-1}") # list of arguments except the last - source directories to scan
for d in "${dir[@]}" ; do if [[ ! -d "$d" ]] ; then echo "source directory $d does not exist - exiting" >&2 ; exit 1 ; fi ; done
lst=${@:$#:1} # last argument - the list with created links (full paths)
if [[ ! -f $lst ]] ; then echo "can't find the file $lst with the list of linked file paths" >&2 ; exit 1 ; fi

if [[ -n $dryrun ]] ; then
	echo "-- scanning source directories ${dir[@]}"
	if [[ -n $trash ]] ; then echo "-- using trash $trash" ; fi
	echo "-- crosschecking and cleanup using file list $lst which contains $(cat "$lst" | wc -l) registered entries"
fi

tmp=$(mktemp) # wipe list (candidates) for directories
tmp1=$(mktemp) ; sort -u "$lst" > $tmp1
tmp2=$(mktemp)

find "${dir[@]}" \( -type f -o -type l \) ! -path "*/@eaDir/*" -print | sort > $tmp2
if [[ -n $dryrun ]] ; then
	echo "-- [ the below should not print '<' items; the '>' items will be deleted by the algorithm"
	diff $tmp1 $tmp2 | grep '^[<>]'
	echo "-- ]"
fi
diff $tmp1 $tmp2 | grep '^>' | sed -e 's/^> //' | while read i ; do
	# we have a file that needs to be (re)moved
	if [[ -n $trash ]] ; then
		if [[ -z $dryrun ]] ; then
			p=$(dirname "$trash") ; q=${i#$p} ; q=$(dirname "$q") # calculate the directory of $i relative to $trash (todo: check what happens if $i or $trash contains ../)
			mkdir -p "$trash/$q"
			mv_with_ea "$i" "$trash/$q"
		else
			echo "moving $i to $trash"
		fi
	elif [[ -h $i ]] ; then # need to check for symlinks first, because a symlink also tests as a file (-f)
		if [[ -z $dryrun ]] ; then rm -v "$i" ; else echo "removing symlink $i" ; fi
	elif [[ -f $i ]] ; then # it is a file, but not a symlink
		if [[ -z $dryrun ]] ; then rm_with_ea "$i" ; else echo "unlinking $i" ; fi
	else
		echo "can not remove $i: not found"
	fi
	echo "$(dirname "$i")" >> $tmp
done

# try to cleanup the directories that may have been left behind - no effect if there's still files in there
if [[ -n $cleanupdirs ]] ; then
	# the sort filters out duplicates (-u) and in reverse (-r) so the directories will be deleted depth-first
	# this is a very efficient method because a) usually, there aren't that many deletes and b) only 1 pass per directory (through using -u)
	sort -u -r $tmp | while read d ; do
		if isemptydir_with_ea "$d" ; then
			if [[ -z $(tag "$d") ]] ; then
				echo "cleanup empty directory $d"
				if [[ -z $dryrun ]] ; then rmdir_with_ea "$d" ; fi
			elif [[ -n $trash ]] ; then
				echo "moving tagged directory $d to $trash"
				if [[ -z $dryrun ]] ; then mv_with_ea "$d" "$trash" ; fi
			else
				echo "keeping empty but tagged directory $d"
			fi
		fi
	done
fi

#echo "$tmp $tmp1 $tmp2"
rm -f $tmp $tmp1 $tmp2

#EOF
